[package]
name = "termcade"
version = "0.1.0"
edition = "2024"
authors = [ "Anirudh Konidala" ]
description = "a collection of terminal arcade games to play when you are bored during that 8 am lecture"
license = "MIT"

repository = "https://github.com/kidskoding/termcade"

[workspace]
members = [
  "games/tetris"
]
resolver = "2"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
